### ISSUE TITLE
Assign a license to library

### ISSUE THREAD

**Issue by hammadk373** [charbonnierg/jetstream.py#8]
Hi @charbonnierg this looks like a very useful library for interacting with Jetstream, that is severely required. I am wondering do you plan on adding a license to the library so that it can be used by other projects?

**Comment by charbonnierg** [comment]
Sorry for the delay,

I don't recommend using this library, as it might break with nats-server >= 2.6.

I recommend you to use https://github.com/charbonnierg/nats.py instead, but the downside is that you cannot have official `nats.py` and my fork at the same time.

That being said, you're free to open a PR with a MIT LICENSE file and I will merge it

**Comment by charbonnierg** [comment]
I'm closing this repository in favor of official nats.py client library which introduced JetStream support some days ago.

Still I added an Apache 2 license to the project (because it reuses code from nats.py which is licensed under Apache 2)
